version: '3.8'

services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    environment:
      - LDAP_ORGANISATION="flaskblog
      - LDAP_DOMAIN=example.org
    ports:
      - "389:389"
    networks:
      - sso

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    ports:
      - "6443:443"
    depends_on:
      - openldap
    networks:
      - sso
networks:
  sso:
    name: flaskblog
